# Generated by Django 3.2.15 on 2022-10-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20221002_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
    ]
